### PR TITLE
F/add windows environment support

### PR DESCRIPTION
**Pull request by AimusSage**
- add cross-spawn package for cross environment compatibility
- add option to specify azure App project language for situations when language cannot be inferred during publish

### CODE REVIEW

**Comment by AimusSage** [comment]
I will fix the messy test situation in this pr

**Comment by ziacik** [comment]
@AimusSage, appreciate your input! Got a couple of points to discuss.

First off, the 'cross-spawn' package looks a bit dated with no updates in the past 4 years. Any specific reason you find it necessary? I thought Node.js's spawn covers Windows too. Nx uses spawn/exec, and it's been working, or did I use it wrong? Can you share what's not working on Windows, so I can try fixing it without 'cross-spawn'?

Now, about specifying language type, I'm a bit unclear. Are you aiming for a non-TypeScript function app, like pure JavaScript? By default, it generates TypeScript, which is then built into JavaScript before publishing. Not sure why you'd pass the language to the publish CLI command. Couldn't find in the docs that the last param of the publish command is meant for language; can you point me there?

**Comment by AimusSage** [comment]
First off, sorry for the late reply, You caught me just after I went on holiday. 

So [there are a few windows specific things that make Spawn(Sync) not work really well on windows](https://nodejs.org/api/child_process.html#spawning-bat-and-cmd-files-on-windows). The issue here is calling npm with it (it is a cmd file on windows). Cross-spawn is a package that handles this for many situations and I agree is not really required. The better solution is probably to keep it simple and use spawnSync with the options {shell:true} always set. [I checked and this is what NX also does](https://github.com/nrwl/nx/blob/003b9613c4257e31be4bcc42a04cad3247f95bb5/packages/create-nx-workspace/src/utils/child-process-utils.ts#L9) and should be enough.

Specifying the language type is another quirk on windows with Azure function core tools that I still don't fully understand but is a real hassle where it sometimes has a problem with the local.settings.json file in the local source not being read correctly. I've now solved it another way in our deployment logic since I agree it is not something that should be part of your code to deal with this oddity.  Strangely there is no official documentation but the [language option does exist]((https://stackoverflow.com/questions/56971869/your-azure-function-app-has-functions-worker-runtime-set-to-node-while-your-loca)) 

In retrospect I think the whole thing can be brought down to updating the spawnSync logic to use shell:true in the options to make it sufficiently compatible on windows. If you agree I can make the PR just for that small change, or alternatively, since it is such a small change you could add it yourself in a future update.

**Comment by ziacik** [comment]
@AimusSage Thanks for the reply. If you wish, you can create the spawnSync PR, or you can wait for me to do it. Either way, thanks!

**Pull request closed without merging**
